apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    run: nginx-app
spec:
  ports:
   - port: 8080
     targetPort: 8080
     #protocol: TCP
  selector:
    run: nginx-app
type: LoadBalancer