apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nginx-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-volume
spec:
  capacity:
    storage: 5Gi
  storageClassName: nginx-storage
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nginx-storage
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
        app: nginx
  serviceName: "nginx"      
  replicas: 3 
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - name: www
          containerPort: 80    
        livenessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 10
        readinessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 10
        resources:
          requests:
              cpu: 250m
              memory: 128Mi
          limits:
              cpu: 1000m
              memory: 256Mi
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
    volumes:
        - name: www
          persistentVolumeClaim:
           claimName: nginx-pvc      
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: "nginx-storage"
      resources:
        requests:
          storage: 2Gi
  