kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-with-pvc
  labels:
    name: nginx-with-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  # selector:
  #   matchLabels:
  #     aws-availability-zone: us-west-2c
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
        app: nginx
  serviceName: "nginx"      
  replicas: 3 
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - name: www
          containerPort: 80    
        livenessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 10
        readinessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 10
        resources:
          requests:
              cpu: 250m
              memory: 128Mi
          limits:
              cpu: 1000m
              memory: 256Mi
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi     

  