apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
  name: sh01test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: sh01test-pvc